server:
  port: 9000
  
spring:
  application:
    name: gateway   
  cloud:
    gateway:
      routes:
      - id: auth
        uri: lb://auth
        predicates:
        - Path=/user/**
        filters:
        - TokenRelay=
      - id: prod
        uri: lb://prod
        predicates:
        - Method=POST,GET
        - Path=/product/**
        filters:
        - TokenRelay=
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring_template
            client-id: spring_template_client
            client-secret: aEmVZ7SmpiZVXx1qnlMi0ElWZiHqJq94
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/user/login
        provider:
         spring_template: 
            issuer-uri: http://localhost:8080/realms/spring_template     
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring_template
          jwk-set-uri: http://localhost:8080/realms/spring_template/protocol/openid-connect/certs  

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/